config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root to: 'posts#index'

   resources :posts do
   resources :comments
   end
   resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user 
end

app/models/post.rb
class Post < ApplicationRecord
   has_one_attached :image
   with_options presence: true do
    validates :title
    validates :place
    validates :content
    validates :image
    
    belongs_to :user
    has_many :comments
    
   end
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments
         validates :name,presence: true
         
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: "Include both letters and numbers"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   before_action :authenticate_user!
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up , keys:[:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
   def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"  
  end
   private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_params, only: %i[ edit update show destory]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new(create_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit; end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end
  

  private
  def create_params
    params.require(:post).permit(:title,:place,:content,:image).merge(user_id: current_user.id)
  end

  def set_params
    @post = Post.find(params[:id])
  end
  
  
end

app/controllers/profiles_controller.rb
class ProfileController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Musk</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <div class="top">
      <div class="left-header">
        <h2 class="letter">Books</h2>
      </div>
      <% if user_signed_in? %>
      <div class="right-header">
        <%= form_with(url: "#", local: true, method: :get, class: "search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= f.submit "検索", class: "search-btn" %>
        <% end %>
        <%= link_to "book", "#", class: "btn" %>
        <%= link_to  "new post", new_post_path, class: "btn" %>
        <%= link_to  "profile", "/users/#{current_user.id}",class: "btn" %>
      </div>
      <% else %>
      <div class="right-header">
        <%= link_to "新規登録", new_user_registration_path, class: "btn" %>
        <%= link_to  "ログイン",new_user_session_path, class: "btn" %>
      </div>
      <% end %>
    </div>
  </header>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

app/views/posts/edit.html.erb
<div class="post">
  <div class="new_post">
    <h1> edit post </h1>
  </div>
  <div class="form">
    <%= form_with model: @post, local: true do |f| %>
    <div class="form_title">
      <%= f.text_field :title,placeholder: "タイトルを入力してください", class: "field_title" %>
    </div>
    <div class="form_place">
      <%= f.text_field :place,class: "field_place",placeholder: "場所を入力してください" %>
    </div>
    <div class="form_content">
      <%= f.text_area :content,class: "field_content",rows: 6,placeholder: "この投稿の詳細文を入力してください" %>
    </div>
    <div class="form_image">
      <%= f.file_field :image,class: "file_field" %>
    </div>
    <div class="form_submit">
      <%= f.submit "Submit" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row mb-2">
  <div class="col-md-6 mx-auto mt-5">
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-success">Lank in</strong>
        <h3 class="mb-0">
          <a class="text-dark" href="#"> Everyone's book</a>
        </h3>
        <div class="mb-1 text-muted">Nov 11</div>
        <p class="card-text mb-auto">This is a book that everyone makes </p>
        <%= link_to  "jump to page",  "#" %>
      </div>
      <img src="assets/boku.jpeg" , class="books-image">
    </div>
  </div>
  <%= @posts.each do |p| %>
  <div class="col-md-6 mx-auto mt-5">
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
      <div class="card-body d-flex flex-column align-items-start p_height">
        <strong class="d-inline-block mb-2 text-success"><%=p.place%></strong>
        <h3 class="mb-0">
          <a class="text-dark p_title" href="#"><%= p.title %></a>
        </h3>
        <h3 class="mb-0">
          <a class="text-dark p_title" href="#"><%= p.content %></a>
        </h3>
        <%= link_to  "jump to page", post_path(@posts.ids), class: "jump_link" %>
      </div>
      <%= image_tag p.image, class: "card-img-right flex-auto d-none d-lg-block image_size" if p.image.attached?%>
    </div>
  </div>
  <%end%>
</div>

app/views/posts/new.html.erb
<div class="post">
  <div class="new_post">
    <h1> new post </h1>
  </div>
  <div class="form">
    <%= form_with model: @post, local: true do |f| %>
    <div class="form_title">
      <%= f.text_field :title,placeholder: "タイトルを入力してください", class: "field_title" %>
    </div>
    <div class="form_place">
      <%= f.text_field :place,class: "field_place",placeholder: "場所を入力してください" %>
    </div>
    <div class="form_content">
      <%= f.text_area :content,class: "field_content",rows: 6,placeholder: "この投稿の詳細文を入力してください" %>
    </div>
    <div class="form_image">
      <%= f.file_field :image,class: "file_field" %>
    </div>
    <div class="form_submit">
      <%= f.submit "Submit" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container show">
  <div class='left-image'>
    <%= image_tag @post.image if @post.image.attached? %>
  </div>
  <div class="right-post">
    <div class="right-title">
      <%= @post.title %>
    </div>
    <div class="right-place">
      <%= @post.place %>
    </div>
    <div class="right-content">
      <%= @post.content %>
    </div>
    <div class="right-comment">
      <strong>コメント</strong>
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8noOQ_eq9cWUG0JIyuClOx1jvoIy-ymnozQ&usqp=CAU">
    </div>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
        <%= comment.text %>
      </p>
      <% end %>
    </div>
    <div class="comment-text">
      <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
      <%= form.submit "SEND" %>
      <% end %>
      <% else %>
      <strong>
        <p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="my_profile">
  <div class="upper">
    <%= @name %>
  </div>
  <div class="lower">
    <%= @posts.each do |p| %>
    <div class="col-md-6 mx-auto mt-5">
      <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start p_height">
          <strong class="d-inline-block mb-2 text-success"><%=p.place%></strong>
          <h3 class="mb-0">
            <a class="text-dark p_title" href="#"><%= p.title %></a>
          </h3>
          <h3 class="mb-0">
            <a class="text-dark p_title" href="#"><%= p.content %></a>
          </h3>
          <%= link_to  "jump to page", post_path(@posts.ids), class: "jump_link" %>
        </div>
        <%= image_tag p.image, class: "card-img-right flex-auto d-none d-lg-block image_size" if p.image.attached?%>
      </div>
    </div>
    <%end%>
  </div>
</div>